package model.utility;

/** Machine-readable interpretations of the canonical condition text. */
public enum QuestConditionType {
    SUN_PRODUCED_IN_DAY,
    ZOMBIES_KILLED_IN_CHAPTER,
    ZOMBIES_KILLED_ONLY_BY_PLANT,
    ZOMBIES_KILLED_ONLY_BY_CACTUS,
    WIN_WITH_MAX_PLANT_LOSSES,
    WIN_WITH_ZERO_SUN,
    KILLS_WITHIN_FIRST_WAVE_SECONDS,
    EXPLOSIVE_PLANTS_USED,
    WIN_WITH_SYMMETRIC_BOARD,
    KILLS_ONLY_BY_PLANT_FAMILY,
    WIN_WITHOUT_PLANT_FAMILY,
    WIN_DAY_LEVEL_WITH_NIGHT_PLANTS,
    MAX_DIFFICULTY_WIN_STREAK,
    FIRST_COLUMN_KILLS_WITHOUT_MOWER,
    WIN_WITH_ASYMMETRIC_BOARD,
    WIN_WITH_ONLY_THREE_SUN_PRODUCERS,
    WIN_WITH_EMPTY_COLUMN,
    WIN_WITH_EMPTY_ROW,
    WIN_WITH_EMPTY_ROW_AND_COLUMN,
    LAWNMOWER_KILLS
}
