plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'pmd'
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['test']
        }
    }
}

dependencies {
    implementation files('lib/gson-2.13.1.jar')

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'Main'
}
tasks.named('run') { standardInput = System.in }
jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

checkstyle {
    toolVersion = '10.17.0'
    configFile = file('config/checkstyle/checkstyle.xml')
    showViolations = true
}

pmd {
    toolVersion = '7.3.0'
    ruleSets = []
    ruleSetFiles = files('config/pmd/pmd-ruleset.xml')
    consoleOutput = true
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType(Pmd).configureEach {
    reports {
        xml.required = true
        html.required = true
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'failed', 'skipped'
    }
}
