package screen.gameplay;

/** Logical animation states seen across plant PAM clip lists. */
public enum PlantAnimationState {
    IDLE, IDLE2, IDLE3, IDLE4, IDLE5,
    ATTACK, ATTACK2, ATTACK3, ATTACK4, ATTACK5,
    SPECIAL, SPECIAL2, SPECIAL3,
    PLANTFOOD, PLANTFOOD_ON, PLANTFOOD_OFF,
    PLANTFOOD_LOOP, PLANTFOOD_LOOP2, PLANTFOOD_START, PLANTFOOD_END, PLANTFOOD_IDLE,
    RELOAD, RELOAD2, RELOAD3,
    DAMAGE, DAMAGE2, DAMAGE3,
    RECOVER, RECOVERY,
    PLANT, PLANT_IDLE,
    CHARGE, BITE, BITE_END,
    INTRO, LOOP, OUTRO,
    WATER
}